language: python
python: 2.7
env:
 - TOX_ENV=py27-django17 COVERALLS=true
 - TOX_ENV=py27-django18 COVERALLS=true
 - TOX_ENV=py27-django19 COVERALLS=true
 - TOX_ENV=docs COVERALLS=false
install:
 - pip install tox
 - pip install python-coveralls
script:
 - tox -e $TOX_ENV
after_success:
 - ./run_coveralls.sh .coverage